/* 
 * Squiggle API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Squiggle.Api;
using Squiggle.Model;
using Squiggle.Client;
using System.Reflection;

namespace Squiggle.Test
{
    /// <summary>
    ///  Class for testing FileTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FileTemplateTests
    {
        // TODO uncomment below to declare an instance variable for FileTemplate
        //private FileTemplate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FileTemplate
            //instance = new FileTemplate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FileTemplate
        /// </summary>
        [Test]
        public void FileTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FileTemplate
            //Assert.IsInstanceOfType<FileTemplate> (instance, "variable 'instance' is a FileTemplate");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Src'
        /// </summary>
        [Test]
        public void SrcTest()
        {
            // TODO unit test for the property 'Src'
        }
        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Test]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

    }

}
