/* 
 * Squiggle API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Squiggle.Api;
using Squiggle.Model;
using Squiggle.Client;
using System.Reflection;

namespace Squiggle.Test
{
    /// <summary>
    ///  Class for testing ModelClient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelClientTests
    {
        // TODO uncomment below to declare an instance variable for ModelClient
        //private ModelClient instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelClient
            //instance = new ModelClient();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelClient
        /// </summary>
        [Test]
        public void ModelClientInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelClient
            //Assert.IsInstanceOfType<ModelClient> (instance, "variable 'instance' is a ModelClient");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'OsName'
        /// </summary>
        [Test]
        public void OsNameTest()
        {
            // TODO unit test for the property 'OsName'
        }
        /// <summary>
        /// Test the property 'PluginVersion'
        /// </summary>
        [Test]
        public void PluginVersionTest()
        {
            // TODO unit test for the property 'PluginVersion'
        }
        /// <summary>
        /// Test the property 'LastCheckin'
        /// </summary>
        [Test]
        public void LastCheckinTest()
        {
            // TODO unit test for the property 'LastCheckin'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

    }

}
