/* 
 * Squiggle API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Squiggle.Api;
using Squiggle.Model;
using Squiggle.Client;
using System.Reflection;

namespace Squiggle.Test
{
    /// <summary>
    ///  Class for testing RenderOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RenderOptionsTests
    {
        // TODO uncomment below to declare an instance variable for RenderOptions
        //private RenderOptions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RenderOptions
            //instance = new RenderOptions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RenderOptions
        /// </summary>
        [Test]
        public void RenderOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RenderOptions
            //Assert.IsInstanceOfType<RenderOptions> (instance, "variable 'instance' is a RenderOptions");
        }

        /// <summary>
        /// Test the property 'AddressId'
        /// </summary>
        [Test]
        public void AddressIdTest()
        {
            // TODO unit test for the property 'AddressId'
        }
        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Test]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }
        /// <summary>
        /// Test the property 'GlobalTemplateId'
        /// </summary>
        [Test]
        public void GlobalTemplateIdTest()
        {
            // TODO unit test for the property 'GlobalTemplateId'
        }
        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }
        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Test]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

    }

}
